# Generated by Django 5.0.3 on 2024-04-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_status_alter_member_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('ALT', 'Alternate')], default='HOME', max_length=4),
        ),
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.CharField(choices=[('NON-OFFICIAL', 'Non-Official'), ('CANDIDATE', 'Candidate'), ('JUNIOR', 'Junior'), ('MIDDLE_SCHOOL', 'Middle School'), ('JUNIOR_VARSITY', 'Junior Varsity'), ('VARSITY', 'Varsity')], default='CANDIDATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('MOBILE', 'Mobile'), ('HOME', 'Home'), ('WORK', 'Work'), ('OTHER', 'Other')], default='MOBILE', max_length=10),
        ),
    ]
