# Generated by Django 5.0.3 on 2024-04-02 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_address_default_phone_default_alter_address_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DUES', 'Dues'), ('FINE', 'Fines'), ('GIFT', 'Gift'), ('OTHER', 'Other')], default='DUES', max_length=5)),
                ('type', models.CharField(choices=[('CHECK', 'Check'), ('CASH', 'Cash'), ('EFT', 'Electronic Funds Transfer')], default='CHECK', max_length=5)),
                ('payment_date', models.DateField()),
                ('notes', models.CharField(max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.season')),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EXAM', 'Examination Results'), ('CRED', 'Credentials'), ('OTHER', 'Other')], default='OTHER', max_length=5)),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.season')),
            ],
        ),
    ]
